---
dist: trusty
sudo: required

matrix:
  fast_finish: true

services:
  - docker

before_install:
  - make build

install: true

script:
  - make test-clean

notifications:
  email:
    on_success: never
    on_failure: never
  webhooks: https://registry.hub.docker.com/u/naftulikay/xenial-vm/trigger/${DOCKERHUB_TOKEN}/
